import type {
  LoyaltyLevelFilter,
  LoyaltyMember,
  LoyaltyMemberLevel,
  LoyaltyMemberStatus,
  LoyaltyMetric,
} from "@/types/loyalty";

export const loyaltyMemberStatusLabels: Record<LoyaltyMemberStatus, string> = {
  activo: "Activo",
  vip: "VIP",
  inactivo: "Inactivo",
};

export const loyaltyMemberLevelLabels: Record<LoyaltyMemberLevel, string> = {
  bronce: "Bronce",
  plata: "Plata",
  oro: "Oro",
  diamante: "Diamante",
};

export const loyaltyLevelFilters: LoyaltyLevelFilter[] = [
  "todos",
  "bronce",
  "plata",
  "oro",
  "diamante",
];

export const loyaltyLevelFilterLabels: Record<LoyaltyLevelFilter, string> = {
  todos: "Todos",
  bronce: "Bronce",
  plata: "Plata",
  oro: "Oro",
  diamante: "Diamante",
};

export const demoLoyaltyMembers: LoyaltyMember[] = [
  {
    id: "loy_001",
    name: "Laura Méndez",
    city: "Madrid",
    email: "laura.mendez@email.es",
    level: "diamante",
    points: 18420,
    visits: 96,
    totalSpend: 12450,
    lastVisit: "2026-07-21",
    status: "vip",
    avatarInitials: "LM",
    avatarColor: "bg-violet-500/20 text-violet-300",
    pointsEarnedThisMonth: 1820,
    rewardsRedeemed: 4,
  },
  {
    id: "loy_002",
    name: "Carlos Ruiz",
    city: "Barcelona",
    email: "carlos.ruiz@email.es",
    level: "oro",
    points: 6420,
    visits: 41,
    totalSpend: 3890,
    lastVisit: "2026-07-21",
    status: "activo",
    avatarInitials: "CR",
    avatarColor: "bg-sky-500/20 text-sky-300",
    pointsEarnedThisMonth: 640,
    rewardsRedeemed: 2,
  },
  {
    id: "loy_003",
    name: "Marina Soler",
    city: "Valencia",
    email: "marina.soler@email.es",
    level: "diamante",
    points: 15280,
    visits: 72,
    totalSpend: 9780,
    lastVisit: "2026-07-19",
    status: "vip",
    avatarInitials: "MS",
    avatarColor: "bg-rose-500/20 text-rose-300",
    pointsEarnedThisMonth: 1340,
    rewardsRedeemed: 5,
  },
  {
    id: "loy_004",
    name: "Javier Ortega",
    city: "Sevilla",
    email: "javier.ortega@email.es",
    level: "plata",
    points: 2180,
    visits: 18,
    totalSpend: 1240,
    lastVisit: "2026-07-08",
    status: "activo",
    avatarInitials: "JO",
    avatarColor: "bg-emerald-500/20 text-emerald-300",
    pointsEarnedThisMonth: 220,
    rewardsRedeemed: 1,
  },
  {
    id: "loy_005",
    name: "Elena Navarro",
    city: "Málaga",
    email: "elena.navarro@email.es",
    level: "bronce",
    points: 640,
    visits: 6,
    totalSpend: 380,
    lastVisit: "2026-07-21",
    status: "activo",
    avatarInitials: "EN",
    avatarColor: "bg-amber-500/20 text-amber-300",
    pointsEarnedThisMonth: 180,
    rewardsRedeemed: 0,
  },
  {
    id: "loy_006",
    name: "Diego Fernández",
    city: "Bilbao",
    email: "diego.fernandez@email.es",
    level: "oro",
    points: 4980,
    visits: 33,
    totalSpend: 2760,
    lastVisit: "2026-04-11",
    status: "inactivo",
    avatarInitials: "DF",
    avatarColor: "bg-indigo-500/20 text-indigo-300",
    pointsEarnedThisMonth: 0,
    rewardsRedeemed: 1,
  },
  {
    id: "loy_007",
    name: "Sofía Romero",
    city: "Zaragoza",
    email: "sofia.romero@email.es",
    level: "diamante",
    points: 9760,
    visits: 58,
    totalSpend: 6540,
    lastVisit: "2026-07-20",
    status: "vip",
    avatarInitials: "SR",
    avatarColor: "bg-fuchsia-500/20 text-fuchsia-300",
    pointsEarnedThisMonth: 980,
    rewardsRedeemed: 3,
  },
  {
    id: "loy_008",
    name: "Pablo Iglesias",
    city: "Alicante",
    email: "pablo.iglesias@email.es",
    level: "plata",
    points: 3010,
    visits: 22,
    totalSpend: 1680,
    lastVisit: "2026-07-16",
    status: "activo",
    avatarInitials: "PI",
    avatarColor: "bg-teal-500/20 text-teal-300",
    pointsEarnedThisMonth: 310,
    rewardsRedeemed: 1,
  },
  {
    id: "loy_009",
    name: "Andrea Castillo",
    city: "Granada",
    email: "andrea.castillo@email.es",
    level: "diamante",
    points: 22140,
    visits: 118,
    totalSpend: 15890,
    lastVisit: "2026-07-21",
    status: "vip",
    avatarInitials: "AC",
    avatarColor: "bg-gold/20 text-gold-light",
    pointsEarnedThisMonth: 2140,
    rewardsRedeemed: 7,
  },
  {
    id: "loy_010",
    name: "Miguel Torres",
    city: "Murcia",
    email: "miguel.torres@email.es",
    level: "bronce",
    points: 290,
    visits: 3,
    totalSpend: 145,
    lastVisit: "2026-07-14",
    status: "activo",
    avatarInitials: "MT",
    avatarColor: "bg-orange-500/20 text-orange-300",
    pointsEarnedThisMonth: 90,
    rewardsRedeemed: 0,
  },
  {
    id: "loy_011",
    name: "Lucía Vargas",
    city: "Valladolid",
    email: "lucia.vargas@email.es",
    level: "oro",
    points: 5540,
    visits: 37,
    totalSpend: 3120,
    lastVisit: "2026-03-22",
    status: "inactivo",
    avatarInitials: "LV",
    avatarColor: "bg-cyan-500/20 text-cyan-300",
    pointsEarnedThisMonth: 0,
    rewardsRedeemed: 2,
  },
  {
    id: "loy_012",
    name: "Hugo Delgado",
    city: "Santander",
    email: "hugo.delgado@email.es",
    level: "plata",
    points: 1870,
    visits: 14,
    totalSpend: 980,
    lastVisit: "2026-07-10",
    status: "activo",
    avatarInitials: "HD",
    avatarColor: "bg-lime-500/20 text-lime-300",
    pointsEarnedThisMonth: 160,
    rewardsRedeemed: 1,
  },
];

function formatTodayKey(date = new Date()) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export function getLoyaltyMetrics(members: LoyaltyMember[]): LoyaltyMetric[] {
  const today = formatTodayKey();
  const activeToday = members.filter((member) => member.lastVisit === today)
    .length;
  const pointsThisMonth = members.reduce(
    (sum, member) => sum + member.pointsEarnedThisMonth,
    0,
  );
  const rewardsRedeemed = members.reduce(
    (sum, member) => sum + member.rewardsRedeemed,
    0,
  );

  return [
    {
      id: "members",
      label: "Miembros del programa",
      value: members.length.toLocaleString("es-ES"),
      icon: "users",
    },
    {
      id: "active-today",
      label: "Clientes activos hoy",
      value: activeToday.toLocaleString("es-ES"),
      icon: "trending-up",
    },
    {
      id: "points-month",
      label: "Puntos entregados este mes",
      value: pointsThisMonth.toLocaleString("es-ES"),
      icon: "award",
    },
    {
      id: "rewards",
      label: "Premios canjeados",
      value: rewardsRedeemed.toLocaleString("es-ES"),
      icon: "gift",
    },
  ];
}
